name: ski-rental
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - anyio=4.9.0
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arviz=0.21.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - atk-1.0=2.38.0
  - attrs=25.3.0
  - babel=2.17.0
  - beautifulsoup4=4.13.3
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - blas=2.131
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.2.25
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=5.5.2
  - cairo=1.16.0
  - certifi=2025.1.31
  - cffi=1.17.1
  - charset-normalizer=3.4.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.2
  - cons=0.4.6
  - contourpy=1.3.1
  - cycler=0.12.1
  - cyrus-sasl=2.1.27
  - dbus=1.13.18
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - etuples=0.3.9
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - expat=2.7.0
  - fastprogress=1.0.3
  - filelock=3.18.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.57.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gcc=13.3.0
  - gcc_impl_linux-64=13.3.0
  - gcc_linux-64=13.3.0
  - gdk-pixbuf=2.42.10
  - gettext=0.23.1
  - gettext-tools=0.23.1
  - glib=2.78.4
  - glib-tools=2.78.4
  - graphite2=1.3.14
  - graphviz=2.49.0
  - gtk2=2.24.33
  - gts=0.7.6
  - gxx=13.3.0
  - gxx_impl_linux-64=13.3.0
  - gxx_linux-64=13.3.0
  - h11=0.14.0
  - h2=4.2.0
  - h5netcdf=1.6.1
  - h5py=3.12.1
  - harfbuzz=4.3.0
  - hdf5=1.14.5
  - hpack=4.1.0
  - httpcore=1.0.7
  - httpx=0.28.1
  - hyperframe=6.1.0
  - icu=73.2
  - idna=3.10
  - importlib-metadata=8.6.1
  - importlib_resources=6.5.2
  - intel-openmp=2022.1.0
  - ipykernel=6.29.5
  - ipython=8.35.0
  - ipywidgets=8.1.6
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9e
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.23.0
  - jsonschema-specifications=2024.10.1
  - jsonschema-with-format-nongpl=4.23.0
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.12.0
  - jupyter_server=2.15.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.0
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.14
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.7
  - krb5=1.20.1
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20250127.0
  - libasprintf=0.23.1
  - libasprintf-devel=0.23.1
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libclang13=14.0.6
  - libcups=2.4.2
  - libcurl=8.12.1
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-devel_linux-64=13.3.0
  - libgcc-ng=14.2.0
  - libgd=2.3.3
  - libgettextpo=0.23.1
  - libgettextpo-devel=0.23.1
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libglib=2.78.4
  - libgomp=14.2.0
  - libiconv=1.18
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm14=14.0.6
  - libltdl=2.4.3a
  - libnghttp2=1.57.0
  - libntlm=1.8
  - libopenblas=0.3.29
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - librsvg=2.54.4
  - libsanitizer=13.3.0
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-devel_linux-64=13.3.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.5.1
  - libtool=2.5.4
  - libuuid=1.41.5
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libxkbcommon=1.8.1
  - libxml2=2.13.7
  - libxslt=1.1.41
  - logical-unification=0.4.6
  - lz4-c=1.9.4
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib=3.10.1
  - matplotlib-base=3.10.1
  - matplotlib-inline=0.1.7
  - mdurl=0.1.2
  - minikanren=1.0.3
  - minizip=4.0.3
  - mistune=3.1.3
  - mkl=2022.1.0
  - mkl-service=2.4.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - mysql=8.4.0
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - notebook=7.4.0
  - notebook-shim=0.2.4
  - nspr=4.36
  - nss=3.89.1
  - numpy=1.24.4
  - openblas=0.3.29
  - openjpeg=2.5.2
  - openldap=2.6.5
  - openssl=3.5.0
  - overrides=7.7.0
  - packaging=24.2
  - pandas=2.2.3
  - pandocfilters=1.5.0
  - pango=1.50.7
  - parso=0.8.4
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.1.0
  - pip=25.0
  - pixman=0.44.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.7
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.50
  - prompt_toolkit=3.0.50
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.1
  - pymc=5.9.2
  - pymc-base=5.9.2
  - pyparsing=3.2.3
  - pyside6=6.7.2
  - pysocks=1.7.1
  - pytensor=2.13.1
  - pytensor-base=2.17.3
  - python=3.10.16
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-graphviz=0.20.3
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.10
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qhull=2020.2
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtshadertools=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebengine=6.7.2
  - qtwebsockets=6.7.3
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.3
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=14.0.0
  - rpds-py=0.24.0
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=75.8.0
  - six=1.17.0
  - sniffio=1.3.1
  - soupsieve=2.5
  - sqlite=3.45.3
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - sysroot_linux-64=2.17
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.14
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.4.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20241206
  - typing-extensions=4.13.2
  - typing_extensions=4.13.2
  - typing_utils=0.1.0
  - tzdata=2025a
  - unicodedata2=16.0.0
  - uri-template=1.3.0
  - urllib3=2.4.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - xarray=2025.3.1
  - xarray-einstats=0.8.0
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-renderutil=0.3.10
  - xkeyboard-config=2.43
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstandard=0.23.0
  - zstd=1.5.6
prefix: /home/hyejun/miniconda3/envs/ski-rental
